repos:
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false

      - id: clippy
        name: cargo clippy --fix
        entry: cargo clippy --all-targets --all-features --fix --allow-dirty --allow-staged -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: test
        name: cargo test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
